name: Daily Processing Workflow
on:
  schedule:
    # Run at 00:00, 06:00, 12:00, and 18:00 UTC every day
    - cron: '0 0,6,12,18 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      run_all_steps:
        description: 'Run all workflow steps'
        required: false
        default: 'true'
      run_collection:
        description: 'Run only data collection'
        required: false
        default: 'false'
      run_generation:
        description: 'Run only content generation'
        required: false
        default: 'false'
      run_publishing:
        description: 'Run only article publishing'
        required: false
        default: 'false'
jobs:
  process_data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create necessary directories
        run: |
          mkdir -p /home/runner/football-predictions/creds/
          mkdir -p data/cache
      
      - name: Setup Firebase credentials
        run: |
          # Salva le credenziali in un file temporaneo per debug
          echo '${{ secrets.FIREBASE_CREDENTIALS }}' > /tmp/firebase_credentials_raw.json
          
          # Verifica che il JSON sia valido
          cat /tmp/firebase_credentials_raw.json | python -c "import sys, json; json.load(sys.stdin)" || echo "Invalid JSON format in FIREBASE_CREDENTIALS"
          
          # Copia le credenziali nella posizione corretta
          cp /tmp/firebase_credentials_raw.json /home/runner/football-predictions/creds/firebase-credentials.json
          
          # Imposta la variabile d'ambiente
          echo "FIREBASE_CREDENTIALS=/home/runner/football-predictions/creds/firebase-credentials.json" >> $GITHUB_ENV
      
      - name: Verify file content and permissions
        run: |
          echo "Checking if credential file exists and is readable"
          ls -la /home/runner/football-predictions/creds/
          cat /home/runner/football-predictions/creds/firebase-credentials.json | head -n 10
        
      - name: Collect match data
        if: ${{ github.event.inputs.run_all_steps == 'true' || github.event.inputs.run_collection == 'true' || github.event_name == 'schedule' }}
        run: |
          python -m scripts.daily_coordinator --collect-data
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          FIREBASE_CREDENTIALS: /home/runner/football-predictions/creds/firebase-credentials.json
