name: Generate Content

on:
  schedule:
    - cron: '0 */6 * * *'  # Ogni 6 ore
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin python-dotenv
          
      - name: Generate articles
        run: python scripts/content_generation/article_generator.py
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          PUBLISH_WINDOW_START: 8
          PUBLISH_WINDOW_END: 6
          
      - name: Translate articles
        run: python scripts/translation/translator.py
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          LANGUAGES: "en,it,es,fr,de,pt,ar,ru,ja,pl,zh,tr,nl,sv,el"
          
      - name: Update health status
        run: |
          echo "Updating health status..."
          python scripts/monitoring/update_health.py --component=content_generation
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
