name: Publish Articles
on:
  schedule:
    - cron: '0 */12 * * *'  # Ogni 12 ore
  workflow_dispatch:  # Permette esecuzione manuale
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin python-dotenv
          
      - name: Publish articles
        run: python -u scripts/publishing/publish_to_wordpress.py
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_URL: ${{ secrets.WP_URL }}
          
      - name: Update health status
        run: |
          echo "Updating health status..."
          python -u scripts/monitoring/update_health.py --component=publishing || echo "Failed to update health status"
        env:
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
