name: System Monitoring
on:
  schedule:
    - cron: '0 */12 * * *'  # Due volte al giorno
  workflow_dispatch:
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin python-dotenv
          
      - name: Run system health check
        run: python scripts/monitoring/system_health_check.py
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          NOTIFICATION_WEBHOOK: ${{ secrets.NOTIFICATION_WEBHOOK }}
          
      - name: Database backup
        run: python scripts/monitoring/backup_database.py
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
